apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: NodePort
  selector:
    app: wordpress-deployment
  ports:
  - port: 3001
    nodePort: 30301
    targetPort: wordpress-port #defined in pod
    protocol: TCP 
